### ISSUE TITLE
[BUG] using inferencer component with appwrite dataprovider

### ISSUE THREAD

**Issue by pinale** [refinedev/refine#3118]
### Describe the bug

Using `inferencer` and `appwrite dataprovider` i got this `warning` message in the browser console, obviously the app doesn't work 
```
Formatting error in inferencer SyntaxError: An identifier or keyword cannot immediately follow a numeric literal. (3:26) (at bundle.js:267985:21)
  1 | import React from "react";import { useDataGrid, DataGrid, GridColumns, EditButton, ShowButton, DeleteButton, List, DateField } from "@pankod/refine-mui";
  2 |         
> 3 |         export const 6357a1b63ef8d80b30c6List = () => {
    |                          ^
  4 |             const { dataGridProps } = useDataGrid();
  5 |         
  6 |             
    at k (bundle.js:267985:21)
```

### Steps To Reproduce

configure resource name with appwrite collectionId e.g: 6357a1b12a5c0d9e41b2
```
function App() {
  return (
    <ThemeProvider theme={LightTheme}>
      <CssBaseline />
      <GlobalStyles styles={{ html: { WebkitFontSmoothing: "auto" } }} />
      <RefineSnackbarProvider>
        <Refine
          dataProvider={dataProvider(appwriteClient, {
            databaseId: "6357a1b12a5c0d9e41b2",  //moviedb
          })}
          liveProvider={liveProvider(appwriteClient, {
            databaseId: "6357a1b12a5c0d9e41b2",
          })}
          liveMode="auto"
          authProvider={authProvider}
          LoginPage={AuthPage}
          notificationProvider={notificationProvider}
          Layout={Layout}
          ReadyPage={ReadyPage}
          catchAll={<ErrorComponent />}
          routerProvider={routerProvider}
          resources={[
            {
              name: "6357a1b63ef8d80b30c6",
              list: MuiListInferencer,
              options: {
                label: 'Movies'
              }
            }
          ]}
        />
      </RefineSnackbarProvider>
    </ThemeProvider>
  );
}
```

### Expected behavior

that app works  :-)

**Comment by omeraplak** [comment]
Hey @pinale ,
Thank you for reporting issue. We'll fix this issue tomorrow ⚡️

**Comment by aliemir** [comment]
Sorry for the issue 🙏 Looks like a case we missed to cover; resource names can start with numbers 😅 Won’t take much time to fix and deploy a new version.

Again, sorry for the trouble and thank you for reporting this issue (and thank you for the feedback you gave last week about the inferencers) 🚀🚀

**Comment by omeraplak** [comment]
Hey @pinale,
We created #3123 and will release it Monday ⚡️

**Comment by omeraplak** [comment]
Hey @pinale ,
We've released @pankod/refine-inferencer@1.2.2. You can update your refine dependencies with `npm run refine update` or `npx @pankod/refine-cli update` commands.

**Comment by pinale** [comment]
hi, 
although the ListInference apparently works

i've got these errors in the browser console

**MuiListInferencer** --> `400 bad request`
```
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$collections/documents/6357a26137534e7f8276
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$databases/documents/6357a1b12a5chi, 
although the ListInference apparently works

i've got these errors in the browser console

**MuiListInferencer** --> `400 bad request`
```
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$collections/documents/6357a26137534e7f8276
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$databases/documents/6357a1b12a5c0d9e41b2
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$database/documents/6357a1b12a5c0d9e41b2
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$collection/documents/6357a26137534e7f8276

{"message":"Invalid collectionId: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore","code":400,"type":"general_argument_invalid","version":"1.1.1"}
```

**MuiEditInferencer**  --> `404 not found`
```
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/6357a1b63ef8d80b30c6/documents/1

{"message":"Document with the requested ID could not be found.","code":404,"type":"document_not_found","version":"1.1.1"}

```

i've configured a simple appwrite collection with an `id (integer)` attribute and a `name (string)` attribute.
i've missing something or there is some other problem with inferencer?

<hr/>

**PS** : other queries like this generated by the inferencer component works

```
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/6357a1b63ef8d80b30c6/documents?queries%5B0%5D=offset%280%29&queries%5B1%5D=limit%2825%29
```

0d9e41b2
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$database/documents/6357a1b12a5c0d9e41b2
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/$collection/documents/6357a26137534e7f8276

{"message":"Invalid collectionId: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore","code":400,"type":"general_argument_invalid","version":"1.1.1"}
```

**MuiEditInferencer**  --> `404 not found`
```
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/6357a1b63ef8d80b30c6/documents/1

{"message":"Document with the requested ID could not be found.","code":404,"type":"document_not_found","version":"1.1.1"}

```

i've configured a simple appwrite collection with an `id (integer)` attribute and a `name (string)` attribute.
i've missing something or there is some other problem with inferencer?

<hr/>

**PS** : other queries like this generated by the inferencer component works

```
http://localhost:81/v1/databases/6357a1b12a5c0d9e41b2/collections/6357a1b63ef8d80b30c6/documents?queries%5B0%5D=offset%280%29&queries%5B1%5D=limit%2825%29
```

**Comment by pinale** [comment]
https://github.com/refinedev/refine/discussions/3046#discussioncomment-4325784
