### ISSUE TITLE
[BUG] create refine-app don't work

### ISSUE THREAD

**Issue by dj-fiorex** [refinedev/refine#3238]
### Describe the bug

 Hello, i'm trying to generate a new refine project with superplate but it gives me this error: 
```
$ npm create refine-app my-project
- Checking provided source "undefined"
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, rename 'C:\Users\user\Desktop\1671094425008-7915057495246989\superplate-core-plugins-master' -> 'C:\Users\user\Desktop\.20221115-9416-l0p3vf.wp48n'
Emitted 'error' event on GithubDownloader instance at:
    at C:\Users\user\AppData\Local\npm-cache\_npx\678fa4c4b5e44e85\node_modules\github-download\lib\github-download.js:131:26
    at C:\Users\user\AppData\Local\npm-cache\_npx\678fa4c4b5e44e85\node_modules\graceful-fs\polyfills.js:111:19
    at callback (C:\Users\user\AppData\Local\npm-cache\_npx\678fa4c4b5e44e85\node_modules\graceful-fs\polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:199:5) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\user\\Desktop\\1671094425008-7915057495246989\\superplate-core-plugins-master',
  dest: 'C:\\Users\\user\\Desktop\\.20221115-9416-l0p3vf.wp48n'
}
```

Tried also with the @latest version, with that i can create a new project but when i need to select the options i didn't see che cursor move, i mean i can select the third element but the green highlighted options didn't change

### Steps To Reproduce

1. run  npm create refine-app my-project

### Expected behavior

I can create new refine project without errors

### Desktop

- OS: windows 11 x64
- NODE: 16.13.1

**Comment by omeraplak** [comment]
Hey @dj-fiorex ,
Could you try the latest version?
`npm create refine-app@latest my-project`

**Comment by dj-fiorex** [comment]
Sure i can provide a video recording but i cannot show you the problem with a video. When i use the latest version the project is created successfully but during the setup the highlighted green option does not move when i click on the keyboard BUT the option will be correct.
Example
If I click 3 times the down arrow the third option will be selected but the highlighted green option does not move

**Comment by omeraplak** [comment]
What do you mean by the third option?

**Comment by dj-fiorex** [comment]
ok, i will give you another example:
First choice of "refine-app" is "Choose a project template"
i CAN select the third option ("refine(Remix)") but  the highlighted green option does not move and remain the first option ("refine(Next,js)")
Do you understand now? Sorry maybe is my rusty english!

**Comment by aliemir** [comment]
Hey @dj-fiorex, sorry for the issue. Can you share the results for `npm create refine-app@latest whoami`? We've tried to reproduce the issue you're facing but had no luck with both on Mac and Windows 🤔

**Comment by aliemir** [comment]
Closing this issue due to inactivity. Do not hesitate to re-open or to create a new issue when you bump into one 🚀
