### ISSUE TITLE
[BUG] Multiple errors with fresh created app with Remix and Mui

### ISSUE THREAD

**Issue by andreystavitsky** [refinedev/refine#3837]
### Describe the bug

After creating app with Remix and Mui console displays multiple errors
```
react-dom.development.js:86 
        
       Warning: Expected server HTML to contain a matching <meta> in <head>.
    at meta
    at head
    at html
    at http://localhost:3000/build/root-QGHZKJ44.js:3781:51
    at App
    at RemixRoute (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:6093:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:4491:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:4867:9)
    at Routes (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:4740:5)
    at Router (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:4687:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:4638:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:5721:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-BT37IK5M.js:7106:55)
printWarning @ react-dom.development.js:86
react-dom.development.js:12507 
        
       Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
2errorBoundaries.js:70 
        
       Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
    at workLoop (scheduler.development.js:266:34)
RemixRootDefaultErrorBoundary @ errorBoundaries.js:70
react-dom.development.js:86 
        
       Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
printWarning @ react-dom.development.js:86
8react-dom.development.js:12507 
        
       Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
    at workLoop (scheduler.development.js:266:34)
2react-dom.development.js:26912 
        
       Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
    at workLoop (scheduler.development.js:266:34)
react-dom.development.js:12507 
        
       Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
    at workLoop (scheduler.development.js:266:34)
react-dom.development.js:19849 
        
       Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19849:57)
    at beginWork (react-dom.development.js:21615:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
query.ts:462 
        
       Query data cannot be undefined. Please make sure to return a value other than undefined from your query function. Affected query key: ["getUserIdentity"]
onSuccess @ query.ts:462
query.ts:444 
        
       Error: undefined
    at Object.onSuccess (query.ts:466:19)
    at resolve (retryer.ts:103:14)
onError @ query.ts:444
```

### Steps To Reproduce

```
yarn create refine-app test
√ Choose a project template · refine-remix
√ What would you like to name your project?: · test
√ Choose your backend service to connect: · data-provider-custom-json-rest
√ Do you want to use a UI Framework?: · mui
√ Do you want to add example pages?: · yes
√ Do you want to add dark mode support?: · mui-dark-mode
√ Do you want an extended theme?: · mui-extend-theme
√ Do you want to customize the Material UI layout?: · mui-custom-layout
√ Do you need any Authentication logic?: · auth-provider-custom
√ Do you want to add kbar command interface support?: · no
√ Choose a package manager: · yarn
```

### Expected behavior

No errors in console output

**Comment by andreystavitsky** [comment]
fix: https://github.com/kiliman/remix-hydration-fix

**Comment by omeraplak** [comment]
Hey @andreystavitsky , 
Thanks for the issue. I think it's due to an incompatibility between MUI and Remix. Refine can't apply the fix you specified, but I'm sure it will be useful to someone in the future. Thanks a lot! ⚡️
