### ISSUE TITLE
<ProviderChildren> nullsafe loading [BUG]

### ISSUE THREAD

**Issue by eugenlinde** [refinedev/refine#5038]
### Describe the bug

Hey!

I discovered this project and was eager to try out refine for the first time.
I tried to setup my first project from both CLI and browser based solution however both cases ended up with the same error.
After running the npm run dev command I get this message:
TypeError: Cannot read properties of null (reading 'firstChild')

I followed the setup guide from the documentation.
I tried googling for a solution and debugging it myself but could not find a proper solution and figured that it might be better to ask for help here.

### Steps To Reproduce

1. start bootstrapping the a new refine app
2. selected stack was remix-ant-restAPI-googleAuth
3. npm install in terminal
4. npm run dev in terminal
5. go to localhost address provided by the terminal

### Expected behavior

Initial npm run dev provides working app.

### Desktop

- macOS
- chrome

### Additional Context

TypeError: Cannot read properties of null (reading 'firstChild')
    at injectCSS (http://localhost:3000/build/_shared/chunk-T2JCWF2Q.js:17832:30)
    at syncRealContainer (http://localhost:3000/build/_shared/chunk-T2JCWF2Q.js:17871:28)
    at updateCSS (http://localhost:3000/build/_shared/chunk-T2JCWF2Q.js:17880:3)
    at http://localhost:3000/build/_shared/chunk-T2JCWF2Q.js:19074:22
    at http://localhost:3000/build/_shared/chunk-T2JCWF2Q.js:18305:67
    at http://localhost:3000/build/_shared/chunk-T2JCWF2Q.js:18205:5
    at commitHookEffectListMount (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:16904:34)
    at commitMutationEffectsOnFiber (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:17700:19)
    at recursivelyTraverseMutationEffects (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:17681:15)
    at commitMutationEffectsOnFiber (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:17695:15)

**Comment by alicanerdurmaz** [comment]
Hello @eugenlinde, I couldn't reproduce the problem. Does your problem still exist?
