### ISSUE TITLE
[BUG] basePath issue with NextJS and MUI

### ISSUE THREAD

**Issue by levipro** [refinedev/refine#5197]
### Describe the bug

Getting console error when using next `basePath` config, links in MUI theme are not reflecting the setting

`Warning: Prop `href` did not match. Server: "/" Client: "/v2/app"`

### Steps To Reproduce

Example repo: https://github.com/levipro/refine-issue

Load dev server (`pnpm dev`) and browse to page [https://localhost:3000/v2/app](https://localhost:3000/v2/app). You may have to refresh with the console open to see the error

### Expected behavior

next basePath should be used for links rendered in theme

### Screenshot

<img width="1740" alt="image" src="https://github.com/refinedev/refine/assets/47224088/09940783-2080-4052-8451-420929e6f6df">

### Additional Context

Warning: Prop `href` did not match. Server: "/" Client: "/v2/app"
    at a
    at LinkComponent (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/link.js:105:19)
    at RefineLink (webpack-internal:///./node_modules/.pnpm/@refinedev+nextjs-router@5.5.4_@refinedev+core@4.44.9_@types+react-dom@18.2.14_@types+react@1_332h6jx4c7mraqofzagyzrqwlq/node_modules/@refinedev/nextjs-router/dist/esm/index.js:169:87)
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Typography (webpack-internal:///./node_modules/.pnpm/@mui+material@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Typography/Typography.js:103:87)
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Link (webpack-internal:///./node_modules/.pnpm/@mui+material@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Link/Link.js:113:83)
    at ThemedTitleV2 (webpack-internal:///./node_modules/.pnpm/@refinedev+mui@5.13.17_@emotion+react@11.11.1_@emotion+styled@11.11.0_@mui+lab@5.0.0-alpha.15_dqezhywbvfalqhpt2asdzserrq/node_modules/@refinedev/mui/dist/esm/index.js:145:51805)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Paper (webpack-internal:///./node_modules/.pnpm/@mui+material@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Paper/Paper.js:79:83)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Paper (webpack-internal:///./node_modules/.pnpm/@mui+material@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Paper/Paper.js:79:83)
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Drawer (webpack-internal:///./node_modules/.pnpm/@mui+material@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Drawer/Drawer.js:155:83)
    at nav
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Box (webpack-internal:///./node_modules/.pnpm/@mui+system@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react@18.2.0/node_modules/@mui/system/esm/createBox.js:37:72)
    at ThemedSiderV2 (webpack-internal:///./node_modules/.pnpm/@refinedev+mui@5.13.17_@emotion+react@11.11.1_@emotion+styled@11.11.0_@mui+lab@5.0.0-alpha.15_dqezhywbvfalqhpt2asdzserrq/node_modules/@refinedev/mui/dist/esm/index.js:145:37296)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Box (webpack-internal:///./node_modules/.pnpm/@mui+system@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react@18.2.0/node_modules/@mui/system/esm/createBox.js:37:72)
    at ThemedLayoutContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+mui@5.13.17_@emotion+react@11.11.1_@emotion+styled@11.11.0_@mui+lab@5.0.0-alpha.15_dqezhywbvfalqhpt2asdzserrq/node_modules/@refinedev/mui/dist/esm/index.js:145:29570)
    at ThemedLayoutV2 (webpack-internal:///./node_modules/.pnpm/@refinedev+mui@5.13.17_@emotion+react@11.11.1_@emotion+styled@11.11.0_@mui+lab@5.0.0-alpha.15_dqezhywbvfalqhpt2asdzserrq/node_modules/@refinedev/mui/dist/esm/index.js:145:49967)
    at UnsavedWarnContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:140:17500)
    at RefineContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:140:8569)
    at UndoableQueueContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:20357)
    at AuditLogContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:149:12452)
    at AccessControlContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:149:3895)
    at TranslationContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:53493)
    at ResourceContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:47941)
    at LegacyRouterContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:149:3183)
    at RouterBindingsProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:48376)
    at LiveContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:47423)
    at DataContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:44321)
    at AuthBindingsContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:140:13937)
    at LegacyAuthContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:140:13059)
    at NotificationContextProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:141:52949)
    at QueryClientProvider (webpack-internal:///./node_modules/.pnpm/@tanstack+react-query@4.36.1_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at Refine (webpack-internal:///./node_modules/.pnpm/@refinedev+core@4.44.9_@tanstack+react-query@4.36.1_@types+react-dom@18.2.14_@types+react@18._z4u6gxv6nkfvqe3ylhk4g3lepa/node_modules/@refinedev/core/dist/esm/index.js:150:25578)
    at L (webpack-internal:///./node_modules/.pnpm/@refinedev+devtools-shared@1.1.2_@types+react-dom@18.2.14_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@refinedev/devtools-shared/dist/esm/index.js:13:1755)
    at he (webpack-internal:///./node_modules/.pnpm/@refinedev+devtools@1.1.22_@refinedev+cli@2.16.14_@refinedev+core@4.44.9_@refinedev+devtools-_eocboa367pbtnjxmjsdeug66ui/node_modules/@refinedev/devtools/dist/esm/index.js:20:183)
    at SnackbarProvider (webpack-internal:///./node_modules/.pnpm/notistack@2.0.8_@emotion+react@11.11.1_@emotion+styled@11.11.0_@mui+material@5.14.15_react-dom@18.2.0_react@18.2.0/node_modules/notistack/dist/notistack.esm.js:739:24)
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.33_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+private-theming@5.14.15_@types+react@18.2.33_react@18.2.0/node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+system@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react@18.2.0/node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:54:5)
    at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+material@5.14.15_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/styles/ThemeProvider.js:27:14)
    at ColorModeContextProvider (webpack-internal:///./src/contexts/index.tsx:24:11)
    at KBarProvider (webpack-internal:///./node_modules/.pnpm/kbar@0.1.0-beta.43_@types+react-dom@18.2.14_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/kbar/lib/KBarContextProvider.js:28:48)
    at RefineKbarProvider (webpack-internal:///./node_modules/.pnpm/@refinedev+kbar@1.3.4_@refinedev+core@4.44.9_@types+react-dom@18.2.14_@types+react@18.2.33_react-dom@18.2.0_react@18.2.0/node_modules/@refinedev/kbar/dist/esm/index.js:29:8169)
    at MyApp (webpack-internal:///./pages/_app.tsx:35:11)
    at I18nextProvider (webpack-internal:///./node_modules/.pnpm/react-i18next@11.18.6_i18next@20.6.1_react-dom@18.2.0_react@18.2.0/node_modules/react-i18next/dist/es/I18nextProvider.js:11:19)
    at AppWithTranslation (webpack-internal:///./node_modules/.pnpm/next-i18next@8.10.0_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-i18next/dist/esm/appWithTranslation.js:37:30)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5389)
    at ReactDevOverlay (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7785)
    at Container (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:78:1)
    at AppContainer (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:207:11)
    at Root (webpack-internal:///./node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:421:11)

**Comment by BatuhanW** [comment]
Hi @levipro thanks for the details and reproducible example! We'll check it and get back to you.

**Comment by BatuhanW** [comment]
Hello @levipro, as a workaround, you can update your `next.config.js` like below:

```
const { i18n } = require("./next-i18next.config");

module.exports = {
  i18n,
  basePath: "/v2/app",
  transpilePackages: ["@refinedev/nextjs-router"]
};
```

Adding `transpilePackages` should fix your issue. We'll explore more on the root cause of this issue.
