### ISSUE TITLE
[BUG] Application does not start after installation, port 5001 error

### ISSUE THREAD

**Issue by barbudour** [refinedev/refine#5215]
### Describe the bug

Hi, when I create a new Refine project (vite, strapi, headless ui) and try to run it in dev mode, I get an error saying that 5001 port is busy and the application cannot start

```bash
npm run dev
> lpg-manager@0.1.0 dev
> refine dev

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                     │
│   — refine Devtools beta version is out! To install in your project, just run npm run refine devtools init.         │
│   https://s.refine.dev/devtools-beta                                                                                │
│                                                                                                                     │
│   — Hello from refine team! Hope you enjoy! Join our Discord community to get help and discuss with other users.    │
│   https://discord.gg/refine                                                                                         │
│                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

✓ refine devtools is running at port 5001

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Function.listen (/Users/barbudour/Decus/lpg/lpg-manager/node_modules/express/lib/application.js:635:24)
    at N (/Users/barbudour/Decus/lpg/lpg-manager/node_modules/@refinedev/devtools-server/dist/index.js:1:1542)
    at We (/Users/barbudour/Decus/lpg/lpg-manager/node_modules/@refinedev/devtools-server/dist/index.js:378:7590)
    at ke (/Users/barbudour/Decus/lpg/lpg-manager/node_modules/@refinedev/cli/dist/cli.js:17:484)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5001
}

Node.js v20.9.0
```

### Steps To Reproduce

1. Create new refine app
2. Select "Vite/Strapi"
3. Install dependencies "npm i"
4. Try "npm run dev"

### Expected behavior

Running refine in dev mode

**Comment by Tegacreatives** [comment]
Check the ID of the process running on that port and you can terminate it using the ID

On mac or Linux, try:

lsof -i :5001

You should get the PID number, then you can proceed to terminate the process using
kill <PID>

On windows, try:

netstat -ano | find "5001"
taskkill /F /PID <PID>

after doing this try running your application again.

**Comment by barbudour** [comment]
I already tried that, but it didn't work for me
<img width="401" alt="image" src="https://github.com/refinedev/refine/assets/29177814/52bde434-14ec-4803-910e-99973341b2f3">

**Comment by BatuhanW** [comment]
Hello @barbudour sorry for the issue, we'll check it and get back to you.

Temporarily, as a workaround you can use `npx kill-port 5001`

**Comment by barbudour** [comment]
Hi @BatuhanW, I tried it, but the error still remains
<img width="748" alt="image" src="https://github.com/refinedev/refine/assets/29177814/6ff05373-bf54-4850-8dff-f94f672cc50e">

**Comment by barbudour** [comment]
Could it be that devtools runs 2 times and can't run the second time because the port is occupied by another instance? And is it possible to disable devtools in general?

**Comment by omeraplak** [comment]
> Could it be that devtools runs 2 times and can't run the second time because the port is occupied by another instance? And is it possible to disable devtools in general?

Hey, when this error occurs, does it also prevent Vite from working? Or is it just preventing DevTools from starting?

**Comment by barbudour** [comment]
Hi @omeraplak, this causes an error that causes the entire Refine application to fail to start. 
I saw this issue, tried adding the argument `devtools=false`, but that didn't work, the errors were identical.

**Comment by omeraplak** [comment]
Thank you for reporting the issue. You can temporarily remove devtools from your project by deleting the `@refinedev/devtools` dependency. We will inform you once we have implemented a permanent solution

**Comment by barbudour** [comment]
@omeraplak removing `@refinedev/devtools` from dependencies helped, thanks

**Comment by michelem09** [comment]
How to change port for devtools? I need 5001 for something else
