### ISSUE TITLE
I'm getting: Warning: [antd: Menu] `children` is deprecated. Please use `items` instead.

### ISSUE THREAD

**Issue by andrei-vaganov** [refinedev/refine#5393]
### Discussed in https://github.com/refinedev/refine/discussions/5379

<div type='discussions-op-text'>

<sup>Originally posted by **andrei-vaganov** December 15, 2023</sup>
Using Antd I'm getting this warning:

`Warning: [antd: Menu] `children` is deprecated. Please use `items` instead. 
    at eval (webpack-internal:///./node_modules/antd/lib/menu/menu.js:36:26)
    at eval (webpack-internal:///./node_modules/antd/lib/menu/index.js:19:37)
    at div
    at aside
    at eval (webpack-internal:///./node_modules/antd/lib/layout/Sider.js:47:18)
    at ThemedSiderV2 (webpack-internal:///./node_modules/@refinedev/antd/dist/esm/index.js:1888:18)
    at Sider
    at div
    at eval (webpack-internal:///./node_modules/antd/lib/layout/layout.js:66:13)
    at Layout
    at ThemedLayoutContextProvider (webpack-internal:///./node_modules/@refinedev/antd/dist/esm/index.js:1173:21)
    at ThemedLayoutV2 (webpack-internal:///./node_modules/@refinedev/antd/dist/esm/index.js:2108:21)
    at UnsavedWarnContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:143:17500)
    at RefineContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:143:8569)
    at UndoableQueueContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:20358)
    at AuditLogContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:152:12418)
    at AccessControlContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:152:3896)
    at TranslationContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:53495)
    at ResourceContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:47943)
    at LegacyRouterContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:152:3184)
    at RouterBindingsProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:48378)
    at LiveContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:47425)
    at DataContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:44324)
    at AuthBindingsContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:143:13937)
    at LegacyAuthContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:143:13059)
    at NotificationContextProvider (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:144:52951)
    at QueryClientProvider (webpack-internal:///./node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at Refine (webpack-internal:///./node_modules/@refinedev/core/dist/esm/index.js:153:25671)
    at div
    at App (webpack-internal:///./node_modules/antd/lib/app/index.js:21:16)
    at MotionWrapper (webpack-internal:///./node_modules/antd/lib/config-provider/MotionWrapper.js:14:5)
    at ProviderChildren (webpack-internal:///./node_modules/antd/lib/config-provider/index.js:126:5)
    at ConfigProvider (webpack-internal:///./node_modules/antd/lib/config-provider/index.js:391:25)
    at ColorModeContextProvider (webpack-internal:///./src/contexts/index.tsx:24:11)
    at KBarProvider (webpack-internal:///./node_modules/kbar/lib/KBarContextProvider.js:28:48)
    at RefineKbarProvider (webpack-internal:///./node_modules/@refinedev/kbar/dist/esm/index.js:29:8169)
    at MyApp (webpack-internal:///./pages/_app.tsx:28:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5389)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7785)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:78:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:182:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:396:11)`
    </div>

**Comment by aliemir** [comment]
Hey @andrei-vaganov, `antd` package started throwing this warning in its v4 but still kept the `children` functioning same after releasing v5. Switching to using `items` takes away the benefits we're getting from JSX. We're using `<CanAccess />` component to check every item of the menu for access control. With giving up the use of `<CanAccess />` I'm not sure if we can have the same performance and implementation when switching to `items`. Btw, the warning is for development mode only and doesn't affect production.

If you have an implementation in mind, feel free to open up a PR but I think we should stick to using `children` if we can 😅
