### ISSUE TITLE
[BUG] Can't run using deno and manual installation

### ISSUE THREAD

**Issue by vadim-su** [refinedev/refine#6335]
### Describe the bug

Cli doesn't work

### Steps To Reproduce

deno run -A --node-modules-dir npm:@refinedev/cli dev

```
error: Uncaught Error: ./package.json not found
    at $ (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:1:1192)
    at L (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:1:1305)
    at h (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:2:3020)
    at Uo (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:2:7920)
    at Yn (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:39:9132)
    at Object.<anonymous> (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:39:9394)
    at Object.<anonymous> (file:///workspace/frontend/node_modules/.deno/@refinedev+cli@2.16.38_1/node_modules/@refinedev/cli/dist/cli.cjs:41:4)
    at Module._compile (node:module:736:34)
    at Object.Module._extensions..js (node:module:757:11)
    at Module.load (node:module:655:32)
```

### Expected behavior

Cli runs dev server

### Packages

- deno 1.46.3
- npm:@refinedev/cli@^2.16.38
- npm:@refinedev/core@^4.54.1
- npm:@types/react@^18.3.5
- npm:@types/react-dom@^18.3.0
- npm:react@^18.3.1
- npm:react-dom@^18.3.1
- npm:vite@^5.4.5

**Comment by aliemir** [comment]
Hey @vadim-su sorry for the issue! Looks like we're having issues when locating the `package.json` in deno environment. This is used by `@refinedev/cli` to provide notifications about the latest version updates and use proper commands and codes in CLI's commands such as `add` and `devtools`. Can you check if replacing `refine dev` command with `vite` in your `package.json` resolves the issue. I'm asking this to make sure other packages don't have any issues in your environment. We can work on updating the logic we use to detect and read `package.json` to work with demo 🤔

**Comment by vadim-su** [comment]
@aliemir Vite works pretty well. Currently, I use `vite dev` for debugging.

**Comment by aliemir** [comment]
I've opened up a PR to fix the issue causing `@refinedev/cli` to crash while initializing. The PR will fix the initial errors letting user be able to use commands such as `devtools start` and `dev` etc. (the platform must be provided with `--platform` such as `--platform vite`). Yet since `@refinedev/cli` is designed to work with `package.json` and handle dependency updates and checks, these features will not work with deno. Considering how deno handles dependencies those features will not be used with deno, so I think we're good to go for now 🎉
