### ISSUE TITLE
[BUG] `create refine-app@latest` does not work with bun (bun.sh) on Windows

### ISSUE THREAD

**Issue by vinhphm** [refinedev/refine#6402]
### Describe the bug

`create refine-app@latest` does not work with bun (bun.sh) on Windows

### Steps To Reproduce

1. Install Bun from bun.sh on Windows with `powershell -c "irm bun.sh/install.ps1 | iex"`
2. Attempt to create a new Refine project with `bun create refine-app@latest`
3. The message with the cow saying `CRUD apps so sleek, even the cows want in! Let's get mooo-ving with Refine!` shows up but then nothing else happens and the script stops.

### Expected behavior

The scripts should continue with the setup process just as in other package managers or operating systems.

### Packages

- [@refinedev/cli@2.16.38](https://github.com/refinedev/refine/releases/tag/%40refinedev%2Fcli%402.16.38)

**Comment by BatuhanW** [comment]
Hey @vinhphm I think it's the same issue with #6335 and should be fixed in #6400. Closing the issue as duplicate for now, feel free to re-open if needed after the release. We plan to do the release latest tomorrow.

**Comment by aliemir** [comment]
Re-opening the issue, related PRs were for `@refinedev/cli`.

@vinhphm, after the cow, does the script ends or keeps running without any output?

**Comment by vinhphm** [comment]
@aliemir The script ends after that the cow without printing anything else.

And I'm not sure if it relates but in existing Refine projects, use Bun to install packages then run `bun start` would cause this as well:

```
$ refine dev
(node:14864) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/modules/cjs/loader:1248
  const err = new Error(message);
              ^

Error: Cannot find module '.bin/vite'
Require stack:
- C:\Users\user\Development\test-project\node_modules\@refinedev\cli\dist\cli.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Function.resolve (node:internal/modules/helpers:145:19)
    at Object.getBin (C:\Users\user\Development\test-project\node_modules\@refinedev\cli\dist\cli.cjs:4:1020)
    at Command.nn (C:\Users\user\Development\test-project\node_modules\@refinedev\cli\dist\cli.cjs:17:1467)
    at Command.listener [as _actionHandler] (C:\Users\pvinh002\Development\test-project\node_modules\@refinedev\cli\node_modules\commander\lib\command.js:482:17)
    at C:\Users\user\Development\test-project\node_modules\@refinedev\cli\node_modules\commander\lib\command.js:1264:65
    at C:\Users\user\Development\test-project\node_modules\@refinedev\cli\node_modules\commander\lib\command.js:1155:33
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\Development\\test-project\\node_modules\\@refinedev\\cli\\dist\\cli.cjs'
  ]
}

Node.js v22.9.0
error: script "start" exited with code 1
```

**Comment by typed-sigterm** [comment]
It's still an issue for me, using Bun v1.2.9 + Refine latest.

Note: Because of the shebang, only `bun --bun dev` can make refine run in Bun
